# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  #config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../app", "/app"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3
    apt-get install -y python-pip
    pip install --upgrade pip
    pip install -r /vagrant/requirements.txt
  SHELL
end
