# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('suffix', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=1)),
                ('hometown', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=10)),
                ('birth', models.DateField(null=True)),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
    ]
