# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('hometown', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=10)),
                ('birth', models.DateField()),
                ('image', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Congressman',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='us.Person')),
                ('state', models.CharField(max_length=2)),
                ('elected', models.DateField()),
            ],
            bases=('us.person',),
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('congressman_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='us.Congressman')),
                ('district', models.IntegerField()),
            ],
            bases=('us.congressman',),
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('congressman_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='us.Congressman')),
                ('seniority', models.CharField(max_length=1)),
            ],
            bases=('us.congressman',),
        ),
    ]
