# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressman',
            name='in_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='suffix',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
