# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_auto_20170203_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressman',
            name='elected',
            field=models.DateField(null=True),
        ),
    ]
